name: deploy-test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      # Dependencies
      - run: npm i -g yarn&&sudo apt update
      - name: Install tools for the .pacman build
        run: sudo apt install -y libarchive-tools
      - name: Install Dependencies
        run: yarn install

      # Testing
      - name: Run ESLint config
        run: yarn lint

      # Build
      - name: Build application
        run: yarn build:linux
        env:
          NEXT_PUBLIC_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_REDIRECT_URI }}

      # Upload
      - name: Remove unwanted files
        run: rm -rf dist/.icon-set dist/linux-unpacked dist/*.yml
      - uses: actions/upload-artifact@v1
        with:
          name: linux
          path: dist

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set env
        run: echo "${{ secrets.ENV_FILE }}" > renderer/.env.local
      - name: Build Dockerfile and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: guusvanmeerveld/voxis-client:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
